blueprint:
  name: Turn off heating after reaching target
  description: >-
    Turn off the heating device if the temperature remains above the target
    temperature for a specified amount of time.
  domain: automation


  input:
    trv_entity:
      name: TRV Entity
      description: The entity ID of the TRV device.
      selector:
        entity:
          domain: climate

    current_temperature_sensor:
      name: Temperature Sensor
      description: The entity ID of the temperature sensor.
      selector:
        entity:
          domain: sensor

    target_temperature_sensor:
      name: Target Temperature Sensor
      description: The entity ID of the target temperature sensor.
      selector:
        entity:
          domain: sensor

    time:
      name: Time
      description: The amount of time the temperature must remain above the target temperature before the heating device is turned off.
      default:
        hours: 1
        minutes: 0
        seconds: 0
      selector:
        duration:
          enable_day: false

    notify:
      name: Notify
      description: The notification service to use.
      selector:
        device:
          integration: mobile_app


variables:
  trigger_template: >-
    {{ states(!input current_temperature_sensor) | float(0) >
    states(!input target_temperature_sensor) | float(0) }}


triggers:
  - platform: template
    value_template: !input trigger_template
    for: !input time


actions:
  - data:
      title: "{{ state_attr(trv_entity, 'friendly_name') }}"
      message: "The temperature has been above the target for {{ !input time }}. The climate device has been turned off."
    action: !input notify
  - target:
      entity_id: !input trv_entity
      action: climate.turn_off
    data: {}
mode: single

